config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Giji::Application.routes.draw do
  mount Sidekiq::Web, at: "/users/7korobi/sidekiq"

  resources :trpg_stories, except: %w[show]

  resources :stories, only: %w[index]
  scope ':folder' do
    resources :stories, only: %w[index]
  end

  scope ':story_id' do
    resources :trpg_events,  except: %w[show]
    get "events" => "messages#file"
    get "file"   => "messages#file", :as => :message_file
    scope ':turn' do
      resources :messages, only: %w[index show]
      resources :trpg_messages, except: %w[show]
    end
  end

  resources :chr_sets
  resources :chr_votes

  resources :users do
    member do
      get  :byebye_list
      get  :history
    end
  end

  namespace :map_reduce do
    resources :faces, only: %w[index show]
  end

  root :to => 'users#index'

end

app/models/request.rb
class Request
  include Giji
  include Mongoid::Timestamps::Created

  field :remote_ip
  field :user_agent
  field :fowardedfor
  has_and_belongs_to_many :sow_auths, inverse_of: nil
  has_and_belongs_to_many :users,     inverse_of: nil

  def self.find_or_create_by(request)
    key = {
      remote_ip:  request.remote_ip,
      user_agent: request.env["HTTP_USER_AGENT"]
    }
    super(key)
  end
end

app/models/user.rb
class User
  include Giji

  def self.find_by_id(id)
    id = BSON::ObjectId.from_string(id) rescue id
    find(id)
  end

  field :_id, default: ->{ user_id }
  field :user_id
  field :name
  field :email
  field :is_admin, type: Boolean
  field :rails_token
  field :sow_auth_ids, as: :sow_auths, type: Array::Line
  field :byebye_ids,   as: :byebyes,   type: Array::Line
  def sow_auth_ids
    self[:sow_auth_ids]
  end
  def byebye_ids
    self[:byebye_ids]
  end

  has_many :auths,    inverse_of: :user

  default_scope -> { where(services:nil) }

  validates_each :sow_auth_ids do |record, field, value|
    if 0 < where(field.in => value.to_a, :user_id.ne => record.user_id).count
      record.errors.add :sow_auths, "already in use."
    end
  end
  validates_uniqueness_of :user_id
  validates_uniqueness_of :email, allow_blank: true

  validates_length_of :user_id, in: 1..30, allow_blank: true, allow_nil: true
  validates_length_of :name,    in: 1..30
  validates_length_of :email,   in: 1..30, allow_blank: true

  def admin?
    is_admin
  end

  def login?
    user_id.present? && name.present?
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-

class UsersController < ApplicationController
  layout "mithril"

  expose(:users_for_admin){ users.order_by(:name.asc) }
  expose(:users){ User }
  expose(:user, attributes: :user_params, finder: :find_by_id)

  respond_to :html, :json

  # show history
  before_action :auth_require, only:%w[new  create]
  before_action :self_require, only:%w[edit update byebye_list]

  def sign_out
    super
  end

  def index
    gon.villages = Rails.cache.fetch("active_stories_view", expires_in: 5.minutes) do
      active_story_ids = SowVillage.where(is_finish:false).pluck(:_id)
      prologue_story_ids = active_story_ids - SowTurn.all.in(story_id: active_story_ids).pluck(:story_id)
      progless_story_ids = active_story_ids - prologue_story_ids
      stories = story_in active_story_ids

      prologue_story_ids.map do |story_id|
        to_message(
          _id: story_id,
          story: stories[story_id].first,
          link:  message_file_path(story_id),
          mestype: "VSAY",
          log: "開始が楽しみだ。",
        )
      end + progless_story_ids.map do |story_id|
        to_message(
          _id: story_id,
          story: stories[story_id].first,
          link:  message_file_path(story_id),
          mestype: "XSAY",
          log: "進行中だ。",
        )
      end
    end
  end

  def show
    if user
      favolite = MapReduce::Face.where("value.sow_auth_id.max_is" => user.id).order_by("value.sow_auth_id.max" => -1).first
      if favolite
        @favolite_face_id = favolite.id
      else
        @favolite_face_id = "undef"
      end
    end
  end

  def byebye_list
    return unless user.sow_auths.present? && user.byebyes.present?

    active_story_ids = SowVillage.where(is_finish:false).pluck(:_id)
    prologue_story_ids = active_story_ids - SowTurn.all.in(story_id: active_story_ids).pluck(:story_id)
#    progless_story_ids = active_story_ids - prologue_story_ids
    user_story_ids   = SowUser.all.in(sow_auth_id: user[:sow_auth_ids] ).in(story_id: prologue_story_ids ).order_by("timer.entrieddt" => 1).pluck(:story_id).uniq
    byebye_story_ids = SowUser.all.in(sow_auth_id: user[:byebye_ids]   ).in(story_id: user_story_ids   ).pluck(:story_id)

    kick_ids = Hash.new {|hash, key| hash[key] = [] }
    maker_story_ids  = SowVillage.where(is_finish:false).in(sow_auth_id: user[:sow_auth_ids] ).pluck(:_id)
    maker_stories = story_in user_story_ids
    maker_stories.each do |story_id, stories|
      story = stories.first
      maker = story.sow_auth_id
      sow_auth_ids = story.potofs.pluck(:sow_auth_id)
      byebyes_by_potof = User.all.in(sow_auth_ids: sow_auth_ids).pluck(:byebye_ids).flatten
      byebyes_by_maker = User.all.in(sow_auth_ids:      [maker]).pluck(:byebye_ids).flatten

      # ５人以上からバイバイされている人
      (byebyes_by_potof & sow_auth_ids).each do |byebye_id|
        kick_ids[story_id].push byebye_id if 4 < byebyes_by_potof.count(byebye_id)
      end

      # 村建て人からバイバイされている人
      (byebyes_by_maker & sow_auth_ids).each do |byebye_id|
        kick_ids[story_id].push byebye_id
      end
    end

    stories = story_in user_story_ids

    gon.byebyes = user_story_ids.map do |story_id|
      story   = stories[story_id].first
      mestype = "VSAY"
      text = "開始が楽しみだ。"
      text = "村を抜けておいたほうがいい。" if byebye_story_ids.member? story_id
      if kick_ids[story_id].present?
        mestype = "WSAY"
        kick_names = SowUser.where(story_id:story_id).in(sow_auth_id:kick_ids[story_id]).pluck(:name)
        text = kick_names.join('、') + "に退去願おう。"
      end

      to_message(
        _id: story_id,
        story: stories[story_id].first,
        link:  message_file_path(story_id),
        mestype: mestype,
        log: text,
      )
    end
  end

  def history
    return unless user.sow_auth_ids
    criteria = SowUser.only(:story_id, :name, :face_id, :csid, :sow_auth_id )
    sow_auth_ids = user.sow_auth_ids - %w[master]

    potofs = criteria.in(sow_auth_id:sow_auth_ids)
    story_ids = potofs.map(&:story_id)
    stories = story_in story_ids

    list = potofs.select do |o|
      story = stories[o.story_id]
      story && story.first.is_finish
    end.sort_by do |o|
      story = stories[o.story_id].first
      0 - story.timer["updateddt"].to_i
    end

    gon.history = list.map do |chr|
      story   = stories[chr.story_id].first
      nation  = GAME[story.folder][:nation] rescue ' - '
      link    = "http://s3-ap-northeast-1.amazonaws.com/giji-assets/stories/#{chr.story_id}"
      created = story.timer["updateddt"]

      chr.attributes.merge(
        _id: chr.story_id,
        name: chr.name,
        user_id: chr.sow_auth_id,
        template: "message/say",
        mestype: "SAY",
        anchor: "#{nation}#{story.vid}",
        style: 'head',
        date: created,
        log: <<_HTML_ ,
<a href="#{link}">#{story.name}</a> <br>
_HTML_
      )
    end
  end

  def new
    p current
    p user
    user.user_id = current.auth.try(:nickname)
    user.name    = current.auth.try(:name)
  end

  def edit
  end

  def create
    if user.save
      flash[:notice] = "successfully #{action_name}d."
      current.auth.user = user
      current.auth.save
      current.user = user
    end
    respond_with user, location:user_path(user.id)
  end

  def update
    if user.save
      flash[:notice] = "successfully #{action_name}d."
    end
    respond_with user
  end

  protected
  def user_params
    params.require(:user).permit(:user_id, :name, :email, :sow_auths, :byebyes)
  end

  def to_message(_id: , story: SowVillage.new, link: message_file_path(story.id), mestype: "SAY", log: "")
    nation  = GAME[story.folder][:nation] rescue ' - '
    created = story["timer"]["updateddt"]

    { template: "message/action",
      mestype:  mestype,
      name:  "#{nation}#{story.vid} #{story.name}",
      style: '',
      updated_at:  created,
      log: log,
      _id: _id
    }
  end

  def story_in(story_ids)
    @stories ||= {}
    @stories[story_ids] ||= SowVillage.only(:_id, :folder, :vid, :name, :timer, :sow_auth_id, :turn, :is_finish).in(_id:story_ids).group_by(&:_id)
  end


  def self?
    super || user.id == current.user.try(:id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
- content_for :navi_head do
  | input users

- content_for :navi do
  .insayfilter(navi="link" name="移動")
    .paragraph
      .sayfilter_caption_enable
        | 他のことを知りたい
      - if user.id
        .sayfilter_content
          li=link_to 'あなたのトップページ', user_path(user.id)

- content_for :log do
  .inframe.toppage
    h2= "#{user.name} さんの情報"

    table.memo.TSAY
      tbody
        tr
          th
            h5
              | アカウント設定
          td
            =semantic_form_for user, html:{class: ""} do |f|
              = f.semantic_errors :sow_auths, :byebyes
              = f.inputs
              = f.input :sow_auths, as: :text, input_html: { rows: 5, cols: 20 }, label: "人狼議事で使っているID"
              = f.input :byebyes, as: :text, input_html: { rows: 5, cols: 20 }, label: "Bye-Bye List"
              .form-group
                = f.actions do
                  = f.submit class: "edge"

app/views/users/_login.html.slim
- content_for :navi do
  .insayfilter(navi="login" name="接続")
    .paragraph
      -if user?
        .sayfilter_caption_enable
          = "login with #{current.auth.provider} account."
        li
          label.label = link_to current.user.name, user_path(current.user.id)
      -if login?
        li
          label.label = link_to '  click to logout', sign_out_path

      .sayfilter_caption_enable
        | Choice open id
      .sayfilter_content
        table#follow
          tr
            td= link_to image_tag('/images/auth/twitter.png',  class: 'twitter'),  '/users/auth/twitter'
            td= link_to image_tag('/images/auth/facebook.png', class: 'facebook'), '/users/auth/facebook'
          tr
            td  Twitter
            td Facebook
        li
          label.label = link_to 'mixi',   '/users/auth/mixi'
        li
          label.label = link_to 'google', '/users/auth/google'
        li
          label.label = link_to 'yahoo',  '/users/auth/yahoo'

app/views/users/byebye_list.html.slim
- content_for :log do
  h2 あなたが参加中の村について
  #byebyes

app/views/users/form.html.slim
- content_for :head do
  h3.sayfilter_heading input users

- content_for :info do
  =semantic_form_for user do |f|
    = f.inputs
    .actions
      = f.submit

- content_for :log do
  h2= "#{user.name} さんの情報"
  =messages_for_auth(user.auths) do |auth|
    table
      tbody
        tr
          th nickname
          td=auth.nickname
        tr
          th name
          td=auth.name

app/views/users/history.html.slim
=render 'login'

- content_for :log do
  h2= "#{user.name} さんの情報"
  #history

app/views/users/index.html.slim
=render 'login'


- content_for :top do

  br
  br
  h2 あなたの情報

  h6
    -if login?
      = "#{current.auth.provider} アカウントを使っています。"
    -else
      = "ログインするIDを選ぼう"

  .paragraph
  -if login?
    .TSAY.action
      p.text
        span.btn.edge = link_to 'ログアウト', sign_out_path

  -if user?
    .TSAY.action
      p.text
        span.btn.edge = link_to "#{current.user.name} さんのページ", user_path(current.user.id)

  -else
    .TSAY.action
      p.text
        table
          tr
            td
              = link_to image_tag('http://s3-ap-northeast-1.amazonaws.com/giji-assets/images/auth/twitter.png',  class: 'twitter'),  '/users/auth/twitter'
            td
              = link_to image_tag('http://s3-ap-northeast-1.amazonaws.com/giji-assets/images/auth/facebook.png', class: 'facebook'), '/users/auth/facebook'
            td
              span.btn.edge = link_to 'mixi',   '/users/auth/mixi'
              span.btn.edge = link_to 'google', '/users/auth/google'
              span.btn.edge = link_to 'yahoo',  '/users/auth/yahoo'

      p.mes_date
        span.mark ByeByeList
        span.mark 参加履歴
        | を使う人は、ログインと、アカウント作成をしましょう。


  h2 みんなの情報

  h6 更新履歴
  .QUE.action
    dt
      .btn.edge
        a(href="https://github.com/7korobi/giji_rails/commits/show-fix") 総合トップ
      .btn.edge
        a(href="https://github.com/7korobi/giji_assets/commits/master") デザイン
      .btn.edge
        a(href="https://github.com/7korobi/sow-giji/commits/cabala") ゲーム
      .btn.edge
        a(href="https://github.com/7korobi/sow-giji/commits/show-fix") ゲーム（新）
    dd
      | 人狼議事を構成するプログラムの、更新履歴はこちら。

  h6 プレイガイド
  .SAY.action
    dt
      .btn.edge
        = link_to "人狼議事のルール", "http://s3-ap-northeast-1.amazonaws.com/giji-assets/assets-master/rule.html"
    dd
      | 人狼議事を遊ぶとき、従うべきルールはこちら。

  h6 キャラクター
  .VSAY.action
    dt
      .btn.edge
        = link_to "キャラクター一覧表", "http://s3-ap-northeast-1.amazonaws.com/giji-assets/assets-master/character_tag.html"
    dd
      | 人狼議事で遊ぶことができるキャラクターはこちら。

  .GSAY.action
    dt
      .btn.edge
        = link_to "キャラクター活躍記録", map_reduce_faces_path
    dd
      | どこかの村で活躍したことのあるキャラクターはこちら。

  
  h6 開始待ちの村／進行中の村
  #villages

  - if admin?
    h2 アカウント一覧
    .paragraph
      = ' / '
      - users_for_admin.each do |user|
        - if (user.sow_auth_ids or []).size > 0
          - if (user.byebye_ids or []).size > 0
            u
              = link_to user.name, user, style:"color:red;"
          - else
            u
              = link_to user.name, user
          = ' / '
        - else
          = link_to user.name, user
          = ' / '

  script
    | window.welcome_navi = "full";

app/views/users/show.html.slim
=render 'login'

- content_for :navi_head do
  | show user

- content_for :top do
  .toppage
    h2= "#{user.name} さんについて"
    .paragraph
      ul
        - if self?
          li
            =link_to '自分のアカウントを編集する', edit_user_path(user)
            ul
              li お使いの人狼議事アカウントを登録して、あなたの参加履歴に簡単アクセス！
          li=link_to 'ByeByeList確認', byebye_list_user_path(user)

        li=link_to '履歴を見る',     history_user_path(user)