config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Giji::Application.routes.draw do
  mount Sidekiq::Web, at: "/users/7korobi/sidekiq"

  resources :trpg_stories, except: %w[show]

  resources :stories, only: %w[index]
  scope ':folder' do
    resources :stories, only: %w[index]
  end

  scope ':story_id' do
    resources :trpg_events,  except: %w[show]
    get "events" => "messages#file"
    get "file"   => "messages#file", :as => :message_file
    scope ':turn' do
      resources :messages, only: %w[index show]
      resources :trpg_messages, except: %w[show]
    end
  end

  resources :chr_sets
  resources :chr_votes

  resources :users do
    member do
      get  :byebye_list
      get  :history
    end
  end

  namespace :map_reduce do
    resources :faces, only: %w[index show]
  end

  root :to => 'users#index'

end

app/controllers/trpg_messages_controller.rb
class TrpgMessagesController < BaseLogController
  expose(:potofs){ story.potofs.where(user_id: current.user.id).cache  }
  expose(:potof)

  expose(:events){ story.events.summary.cache }
  expose(:event){  story.events.where(turn: params[:turn]).cache.first }
  expose(:messages){ event.messages.summary.cache }

  expose(:trpg_messages){ messages }
  expose(:trpg_message)


  respond_to :html, :json

  def index
    gon.messages = messages.gon
    gon.turn = event.turn
  end
end

app/views/trpg_messages/index.html.slim
=render template:'messages/index'


- content_for :navi do
  .insayfilter(navi="info" name="情報")
    .paragraph
      br
      p= event.human_state

-if self?
  - content_for :navi do
    .insayfilter(navi="info" name="操作")
      .paragraph
        p GameMaster

        p= link_to '章を書き換える', edit_trpg_event_path(story, event)
        =semantic_form_for_resource event do |f|
          .inputs
            = f.input :potofs, as: :check_boxes, collection: story.potofs, label: '参加者一覧'
          .actions
            = f.submit

- content_for :log do
  h2= story.name
  h3= event.name
  br
  #messages

  h3
  h3 エントリー
  =semantic_form_for_resource event do |base|
    =base.semantic_fields_for :potof do |f|
      .formpl_frame
        table.formpl_common
          tr.say
            td.img
              img(name="chr_img" src="/images/portrate/undef.jpg")
            td.field
              .msg
                .formpl_content
                  = f.input :face_id, as: :select, collection: Face.all, label: '希望する配役：'
                .formpl_content
                  = f.submit "このシーンに参加"
        .clearboth
          hr.invisible_hr


  table.formpl_common
    tr.say
      td.img
        img alt="" height="130" src="/images/portrate/undef.jpg" width="90"
          td.field
            .msg
              .formpl_content
                | 村長 アルフレッド (
                a href="http://utage.family.jp/WebRecord/user/show?user=a37"
                | ) 魔術師
              form action="./sow.cgi" method="post"
                .formpl_content
                  input name="cmd" type="hidden" value="vote"
                    select name="entrust"
                      option selected="" value=""
                      option value="on"
                    select#selectvote name="target"
                      option value="73"
                    input disabled="" type="submit" value="変更"
              form action="./sow.cgi" method="post"
                .formpl_content
                  textarea cols="30" name="mes" rows="5"
                  br
                    input name="cmd" type="hidden" value="writepr"
                      input disabled="" type="submit" value="発言 / 更新"
                        select name="target"
                          option value="-1"
                          option value="38"
                        select name="monospace"
                          option value=""
                            | (通常)
                          option value="monospace"
                            | 等幅
                          option value="report"
                            | 見出し
                        br
            .msg
              form action="./sow8.cgi" method="post"
                .formpl_action
                  | アルフレッドは、
                  select name="target"
                    option value="-1"

                    option value="73"
                  br
                    fieldset.action_type
                      legend アクション内容
                      select name="actionno"
                        option value="-99"
                        option value="0"
                        option value="42"
                        option value="-4"
                        option value="-5"
                        option value="-2"
                      br
                        input name="cmd" type="hidden" value="action"
                          input.formpl_actiontext name="actiontext" size="30" type="text" value=""
                            br
                    input disabled="" type="submit" value="アクション"
                      | あと
  .clearboth
    hr.invisible_hr
  .formpl_gm
  table.WIN_WOLF
    tr.say
      td
        form action="./sow.cgi" method="post"
          .formpl_content
            input name="cmd" type="hidden" value="role"
              label for="selectrole"
              select#selectrole name="target"
                option value="-2"
                option value="73"
              input disabled="" type="submit" value="変更"
        .formpl_content
        .formpl_content
        hr.invisible_hr