config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Giji::Application.routes.draw do
  mount Sidekiq::Web, at: "/users/7korobi/sidekiq"

  resources :trpg_stories, except: %w[show]

  resources :stories, only: %w[index]
  scope ':folder' do
    resources :stories, only: %w[index]
  end

  scope ':story_id' do
    resources :trpg_events,  except: %w[show]
    get "events" => "messages#file"
    get "file"   => "messages#file", :as => :message_file
    scope ':turn' do
      resources :messages, only: %w[index show]
      resources :trpg_messages, except: %w[show]
    end
  end

  resources :chr_sets
  resources :chr_votes

  resources :users do
    member do
      get  :byebye_list
      get  :history
    end
  end

  namespace :map_reduce do
    resources :faces, only: %w[index show]
  end

  root :to => 'users#index'

end

app/models/trpg_story.rb
class TrpgStory < Story
  belongs_to :user

  field :is_finish, type:Boolean
  has_many :events, inverse_of: :story, class_name: 'TrpgEvent'
  has_many :potofs, inverse_of: :story, class_name: 'TrpgPotof'

  def save
    unless self.vid
      self.vid = self.class.max(:vid).to_i + 1
      self.folder = 'TRPG'
      self.is_finish = false
    end
    super
  end
end

app/controllers/trpg_stories_controller.rb
class TrpgStoriesController < ApplicationController
  expose(:stories){ TrpgStory.page params[:page] }
  expose(:story)

  expose(:trpg_stories){ stories }
  expose(:trpg_story)

  respond_to :html, :json

  before_action :login_require
  before_action :sign, only:%w[create, update]

  def index
    gon.page = { length: stories.num_pages }
  end

  def new
    trpg_story.attributes = TRPG[:default_story]
  end

  def edit
  end

  def create
    if trpg_story.save
      flash[:notice] = "successfully #{action_name}d."
    end
    respond_with story
  end

  def update
    if trpg_story.save
      flash[:notice] = "successfully #{action_name}d."
    end
    respond_with story
  end

  protected
  def self?
    super || trpg_story.user_id == current.user.try(:id)
  end
  def sign
    trpg_story.user_id = current.user.id
  end

  protected
  class Responder < ActionController::Responder
    def navigation_location
      @controller.trpg_events_url @controller.story.id
    end
  end
  def self.responder
    Responder
  end
end

app/views/trpg_stories/_form.html.slim
- content_for :navi_head do
  | 物語を綴る

- content_for :navi do
  .insayfilter(navi="info" name="解説")
    .paragraph
  | さあ、物語を皆に紹介しよう。

- content_for :log do
  =semantic_form_for story do |f|
    h2 物語の説明
    .mes_maker
      = f.input :name
      = f.input :comment, as:'text'
    .actions
      = f.submit

app/views/trpg_stories/edit.html.slim
=render 'form'

app/views/trpg_stories/index.html.slim
=render template:'stories/index'
- content_for :navi do
  .insayfilter(navi="link" name="移動")
    .paragraph
      p ここは物語を収めた図書館。
      p もし新しい物語を綴りたくなったら、扉を開くといい。
      br
      p= link_to '新しい物語の扉を開く', new_trpg_story_path

app/views/trpg_stories/new.html.slim
=render 'form'