config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Giji::Application.routes.draw do
  mount Sidekiq::Web, at: "/users/7korobi/sidekiq"

  resources :trpg_stories, except: %w[show]

  resources :stories, only: %w[index]
  scope ':folder' do
    resources :stories, only: %w[index]
  end

  scope ':story_id' do
    resources :trpg_events,  except: %w[show]
    get "events" => "messages#file"
    get "file"   => "messages#file", :as => :message_file
    scope ':turn' do
      resources :messages, only: %w[index show]
      resources :trpg_messages, except: %w[show]
    end
  end

  resources :chr_sets
  resources :chr_votes

  resources :users do
    member do
      get  :byebye_list
      get  :history
    end
  end

  namespace :map_reduce do
    resources :faces, only: %w[index show]
  end

  root :to => 'users#index'

end

app/models/chr_set.rb
class ChrSet
  include Giji

  field :_id, default: ->{ chr_set_id }
  field :chr_set_id
  field :maker
  field :admin

  embeds_many  :chr_jobs, inverse_of: :chr_set
  embeds_many  :chr_npcs, inverse_of: :chr_set
  accepts_nested_attributes_for :chr_jobs
  accepts_nested_attributes_for :chr_npcs

#  default_scope order_by(:chr_set_id.asc)

  validates_length_of :maker,    in: 1..20
  validates_length_of :admin,    in: 1..20

  def faces
    Face.where(:face_id.in => face_ids )
  end
  def face_ids
    chr_jobs.map(&:face_id)
  end
end

app/controllers/chr_sets_controller.rb
class ChrSetsController < ApplicationController
  expose(:chr_sets){ ChrSet.all }
  expose(:chr_set)

  respond_to :html, :json

  before_action :admin_require, only:%w[new create edit update destroy]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if chr_set.save
      flash[:notice] = "successfully #{action_name}d."
    end
    respond_with chr_set
  end

  def update
    if chr_set.update_attributes(params[:chr_set])
      flash[:notice] = "successfully #{action_name}d."
    end
    respond_with chr_set
  end

  def destroy
    chr_set.destroy
    respond_with chr_set
  end
end

app/helpers/chr_sets_helper.rb
module ChrSetsHelper
end

app/views/chr_sets/_form.html.haml
= simple_form_for chr_set do |f|
  -if chr_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(chr_set.errors.count, "error")} prohibited this chr_set from being saved:"
      %ul
        - chr_set.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/chr_sets/_form.html.slim
=semantic_form_for chr_set do |f|
  =f.object.id
  =f.inputs

  =f.semantic_fields_for :chr_npcs do |nf|
    =nf.object_name
    =nf.object.id
    =nf.inputs
    -nf.object.npc.each do |value|
      ul
        li=text_field_tag "#{nf.object_name}[npc][]", value
  p.command= link_to 'NPCを追加する'

  =f.semantic_fields_for :chr_jobs do |jf|
    =jf.object.id
    =jf.inputs
  p.command= link_to '肩書きとキャラクターを追加する'

  .actions
    = f.submit 'Save'

app/views/chr_sets/edit.html.haml
%h1 Editing chr_set

= render 'form'

= link_to 'Show', chr_set
\|
= link_to 'Back', chr_sets_path

app/views/chr_sets/edit.html.slim
- content_for :navi_head do
  Listing chr_sets

- content_for :navi do
  .insayfilter(navi="info" name="名簿")
    .paragraph
      .sayfilter_caption_enable
        = render 'form'
      .sayfilter_caption_enable
        = link_to 'Show', chr_set
      .sayfilter_caption_enable
        = link_to 'Back', chr_sets_path

app/views/chr_sets/index.html.slim
- content_for :navi_head do
  Listing chr_sets

- content_for :info do
  table
    - chr_sets.each do |chr_set|
      tr
        td.id= link_to chr_set.id, chr_set
        td
          .maker= chr_set.maker
          .admin= chr_set.admin
        td
          .command= link_to 'Edit', edit_chr_set_path(chr_set)
          .command= link_to 'Destroy', chr_set, confirm: 'Are you sure?', method:'delete'

  .sayfilter_caption_enable
    br
    = link_to 'New Chr set', new_chr_set_path

app/views/chr_sets/new.html.haml
%h1 New chr_set

= render 'form'

= link_to 'Back', chr_sets_path

app/views/chr_sets/new.html.slim
= render 'form'

= link_to 'Back', chr_sets_path

app/views/chr_sets/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_chr_set_path(chr_set)
\|
= link_to 'Back', chr_sets_path

app/views/chr_sets/show.html.slim
- content_for :navi_head do
  h3.sayfilter_heading view chr_sets

- content_for :navi do
  .insayfilter(navi="info" name="名簿")
    .paragraph
      .sayfilter_caption_enable
        = link_to 'Edit', edit_chr_set_path(chr_set)
      .sayfilter_caption_enable
        = link_to 'Back', chr_sets_path